// app/env.ts

export const env = {
  NEXT_PUBLIC_UMAMI_URL: "",
  NEXT_PUBLIC_UMAMI_WEBSITE_ID: "",
  GITHUB_TOKEN: "",
  SPOTIFY_CLIENT_ID: "",
  SPOTIFY_CLIENT_SECRET: "",
  SPOTIFY_REFRESH_TOKEN: "",
  LASTFM_API_TOKEN: "",
  WAKATIME_API_KEY: "",
  DISCORD_WEBHOOK_URL: "",
};